version: '2'

services:
  jenkins:
    image: devopsnext/simpleci:0.1
    links: 
      - template-creation
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/jenkins_volume:/d/devops/projects/devopsnext/docker-vol/jenkins

  template-creation:
    image: devopsnext/simpleci-template-creation:0.1
    ports:
      - '8000:8000'
    volumes:
      - /var/jenkins_volume:/d/devops/projects/devopsnext/docker-vol/jenkins
